### ISSUE TITLE
SIGSEGV/Unmarshal json

### ISSUE THREAD

**Issue by uBadRequest** [lc/gau#4] opened 2020-04-22 23:36 UTC
Been getting a bunch of errors that look like this. If it helps, i'm trying to run this in parallel...  Any idea?

```
       /root/go/src/github.com/lc/gau/gau.go:132 +0x1e7
main.Run(0x7fff09682390, 0x17)
        /root/go/src/github.com/lc/gau/gau.go:62 +0xb8
main.main()
        /root/go/src/github.com/lc/gau/gau.go:53 +0x1b9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x661a27]

goroutine 1 [running]:
main.getWaybackUrls(0x7ffeccdf538d, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/lc/gau/gau.go:132 +0x1e7
main.Run(0x7ffeccdf538d, 0x1a)
        /root/go/src/github.com/lc/gau/gau.go:62 +0xb8
main.main()
        /root/go/src/github.com/lc/gau/gau.go:53 +0x1b9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x661a27]

Error: error getting current commoncrawl url: could not unmarshal json from CC: invalid character '<' looking for beginning of value
Error: error getting current commoncrawl url: could not unmarshal json from CC: invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x661a27]

goroutine 1 [running]:
main.getWaybackUrls(0x7ffc73e6b38e, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/lc/gau/gau.go:132 +0x1e7
main.Run(0x7ffc73e6b38e, 0x19)
        /root/go/src/github.com/lc/gau/gau.go:62 +0xb8
main.main()
        /root/go/src/github.com/lc/gau/gau.go:53 +0x1b9
Error: error getting current commoncrawl url: could not unmarshal json from CC: invalid character '<' looking for beginning of value
Error: error getting current commoncrawl url: could not unmarshal json from CC: invalid character '<' looking for beginning of value
Error: error getting current commoncrawl url: could not unmarshal json from CC: invalid character '<' looking for beginning of value
Error: error getting current commoncrawl url: could not unmarshal json from CC: invalid character '<' looking for beginning of value
```

**Comment by lc** [comment] 2020-04-22 23:38
Hey @uBadRequest,

You might be running out of memory, for the "could not marshal json" errors? I can add HTTP request retries to get the common crawl index.

**Comment by lc** [comment] 2020-04-22 23:39
Can you share the command you were using to run this in parallel?

**Comment by lc** [comment] 2020-04-23 17:58
@uBadRequest,

I think I may have fixed the issue. Can you re-install this new version and test?

**Comment by iTestAndroid** [comment] 2020-04-23 21:46
Same for me with even with your last commit.
"could not unmarshal json from commoncrawl: invalid character '<' looking for beginning of value"

**Comment by lc** [comment] 2020-04-23 21:47
@iTestAndroid,

That is an expected error when CommonCrawl rate-limits you. The fix was meant to help with the panic

**Comment by iTestAndroid** [comment] 2020-04-23 21:51
@lc 
Can I disable CommonCrawl? Can I limit pages?

**Comment by lc** [comment] 2020-04-23 21:53
@iTestAndroid, I thought about implementing this recently. I can add a flag that allows you to specify which ones you want to use

**Comment by iTestAndroid** [comment] 2020-04-23 21:55
Sure, I tried to remove CC as I only want the OTX, but I think I messed up some other parts of code. Switch would help, alternatively when you hit the CC limit, it can continue instead of breaking or something

**Comment by lc** [comment] 2020-04-23 21:59
Hey @iTestAndroid,
If you only want URLs from OTX you can alternatively use this tool: http://github.com/lc/otxurls

I'll add limiting the fetchers to my todo list.

**Comment by iTestAndroid** [comment] 2020-04-23 22:00
Great, thanks.
Also I commented out CommonCrawl and I still got this:
"error in parsing JSON from alienvault: invalid character '<' looking for beginning of value"
and
"could not decoding response from wayback machine: net/http: request canceled (Client.Timeout exceeded while reading body)"

**Comment by iTestAndroid** [comment] 2020-04-23 22:02
@lc Am I missing something?
I tried otxurls and I still got this:

2020/04/23 18:00:54 Could not decode json: invalid character '<' looking for beginning of value

**Comment by lc** [comment] 2020-04-23 22:03
Yeah that happens when AlienVault's OTX does not respond with JSON. You might just be getting IP-blocked / rate-limited. Maybe try from another IP

**Comment by iTestAndroid** [comment] 2020-04-23 22:04
@lc 
But when I manually open and type the URL in my browser I can clearly see the JSON data
https://otx.alienvault.com/api/v1/indicators/hostname/google.com/url_list?limit=50&page=1

**Comment by lc** [comment] 2020-04-23 22:57
Many concurrent requests might be blocked, not 100% sure however the error catching is as intended

**Comment by iTestAndroid** [comment] 2020-04-24 21:21
@lc 
Can we slow it down so it works? One thread at time or something?

**Comment by lc** [comment] 2020-04-24 21:23
@iTestAndroid, it currently runs on one thread, but I could add an option to set the delay between the fetchers

**Comment by iTestAndroid** [comment] 2020-04-25 16:05
@lc 
Sure, but I'm not 100% sure that is the problem with the feed. Also if you read 200 pages and page number 201 doesn't work or return wrong JSON, don't break. Maybe exception handling and then returning list of all URLs code was able to capture so far?

**Comment by lc** [comment] 2020-04-25 18:44
Hey @iTestAndroid @uBadRequest,

I just merged a great pull-request that should fix these issues.

Closing this now

**Closed by lc** 2020-04-25 18:44 UTC

**Comment by lc** [comment] 2020-04-26 05:06
@iTestAndroid, I just added the `-providers` flag as well now so you can specify which providers you want to fetch URLs from.

**Comment by iTestAndroid** [comment] 2020-04-27 17:34
All working well now. Thank you
